# version: "3.7"

# services:
#   b2b-front:
#     image: chodzi/b2bcalculator:latest
#     container_name: b2b-calculator
#     volumes:
#       - "/app/node_modules"
#       - ".:/app"
#     restart: always


services:
  b2b-calculator:
    # build: .
    image: chodzi/b2bcalculator:latest
    container_name: b2b-calculator
    ports:
      - "6950:80"  # Expose on 8080 or any available port
    restart: unless-stopped
