version: "3.7"

services:
  b2b-front:
    image: chodzi/b2bcalculator:latest
    container_name: b2b-calculator
    ports:
      - "8100:80"
    volumes:
      - "/app/node_modules"
      - ".:/app"
