apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: b2b-calculator-web-pdb
  namespace: b2b-calculator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: b2b-calculator-web
