name: Deploy Angular App

on:
  push:
    branches:
      - develop  # or your deployment branch

jobs:
  build-and-deploy:
    # runs-on: ubuntu-latest
    # runs-on: self-hosted
    runs-on: wsl

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t chodzi/b2bcalculator:latest .
        docker push chodzi/b2bcalculator:latest

    - name: SSH into Server and Pull
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker pull chodzi/b2bcalculator:latest
          docker stop b2b-calculator || true
          docker rm b2b-calculator || true

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker run -d --restart unless-stopped --name b2b-calculator -p 6950:80 chodzi/b2bcalculator:latest
