name: Build and Deploy with Portainer

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t chodzi/b2bcalculator:latest .
        docker push chodzi/b2bcalculator:latest

    - name: Portainer Webhook call
      run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}

    - name: Update Portainer Stack
      run: |
        curl -X POST "${{ secrets.PORTAINER_URL }}/api/stacks/{stack_id}/deploy" \
          -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}"
